In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install transformers

# **data preparation**

In [ ]:
from dataclasses import dataclass
import string , random

@dataclass
class Data_Config:
  data_path : str = None
  # task of data / purpose of data
  data_kind : str = None
  # Number of data
  sample_num : int = None
  # How many data will be loaded in Dataset
  chunk : int = None
  name : str = None

  token_key : str = None
  token_id : int = None

  data_structure : tuple | None = ("question" , "reference" , "answer")

  # what is field()?

# **processing tokenizer**

In [ ]:
import re
import time
from typing import List , Dict

class Tokenizer:
  def __init__(self , data_name : str = None , dictionary : dict[str , str] = {}) -> list[int | None]:
    self.data_name = data_name
    self.dictionary = dictionary
    self.max_count = int(len(self.dictionary)) if self.dictionary is not None else 0

  # tokenize -> encoder
  def tokenize(self,num_samples : list[str | None] = None) -> list[str | None]:

    # need parallel since it is one by one and take long time and it's inefficient

    for text in num_samples:

      # #, ##, ### 제거
      text = re.sub(r"#+", " ", text)

      # 영어 단어와 문장부호를 각각 추출
      raw_tokens = re.findall(
          r"[A-Za-z]+|[.,!?;:()]",
          text,
      )

      tokens = []

      for token in raw_tokens:
        match = re.fullmatch(
          r"([A-Za-z]+?)(ing|ed)",
          token,
          flags=re.IGNORECASE,
        )

        if match:
          tokens.append(match.group(1))
          tokens.append(match.group(2))
        else:
          tokens.append(token)

    return tokens

  def tokenizer_encoding(self , text_list : list[str | None]) -> Dict:

    for sample in text_list:
      # since dict is hash table, its O(1) in searching
      if sample not in self.dictionary:
        self.max_count += 1
        self.dictionary[sample] = int(self.max_count)
    return self.dictionary

  def inserting_special_token(self, special_token : str | None = None):
    assert type(special_token) == str, "Warning! special_token you added is not str."
    if isinstance(special_token , str):
      self.dictionary[special_token] = self.max_count + 1


  def print_max_num_encoder_dictionary(self):
    print(f"whole number of tokens/index of dictionary : {self.max_count}")

Might be good to mapping natural language to index with semantic criteria

In [ ]:
dictionary = {'son' : 1, 'daughter' : 2}
print(len(dictionary))
tokenizer = Tokenizer(dictionary=dictionary)
tokens=tokenizer.tokenize(['I want to go to school but yesterday there was ##.','I want to go to school but yesterday there was ##.'])
dic_token=tokenizer.tokenizer_encoding(tokens)
print(dic_token)
tokenizer.print_max_num_encoder_dictionary()
type(dic_token['there'])

2
{'son': 1, 'daughter': 2, 'I': 3, 'want': 4, 'to': 5, 'go': 6, 'school': 7, 'but': 8, 'yesterday': 9, 'there': 10, 'was': 11, '.': 12}
whole number of tokens/index of dictionary : 12


int

# **processing positional embedding**

q, k: [batch_size, num_heads, sequence_length, head_dim]

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision , torchaudio

class Positional_Embedding(nn.Module):

  def __init__(self , context_length , head_dim):
    super().__init__()
    self.context_length = context_length
    self.head_dim = head_dim

    if head_dim % 2 != 0:
      raise ValueError("head_dim should be even")

    p = torch.arange(0, context_length , 1, dtype=torch.float32)
    p=p[None,None,:,None]

    i=torch.arange(0, head_dim , 2, dtype = torch.float32)

    tmp_frequency = 10000 ** (((-1) * i) / head_dim)
    tmp_frequency=tmp_frequency[None,None,None,:]

    # frequency *=p , frequency might not change its shape so it could make error. need to use new variable.
    frequency = tmp_frequency * p

    self.register_buffer(
      "frequency",
      frequency,
      persistent=False,
    )

  def apply_positional_embedding(self, query, key):


    for idx , i in enumerate(0, )





In [101]:
import torch
head_dim = 16
context_length = 4
p = torch.arange(0, context_length , 1, dtype=torch.float32)
p=p[None,None,:,None]

i=torch.arange(0, head_dim , 2, dtype = torch.float32)

frequency = 10000 ** (((-1) * i) / head_dim)
frequency=frequency[None,None,None,:]

new=p*frequency
print(p)
print(frequency)
print(new)

tensor([[[[0.],
          [1.],
          [2.],
          [3.]]]])
tensor([[[[1.0000e+00, 3.1623e-01, 1.0000e-01, 3.1623e-02, 1.0000e-02,
           3.1623e-03, 1.0000e-03, 3.1623e-04]]]])
tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
           0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.0000e+00, 3.1623e-01, 1.0000e-01, 3.1623e-02, 1.0000e-02,
           3.1623e-03, 1.0000e-03, 3.1623e-04],
          [2.0000e+00, 6.3246e-01, 2.0000e-01, 6.3246e-02, 2.0000e-02,
           6.3246e-03, 2.0000e-03, 6.3246e-04],
          [3.0000e+00, 9.4868e-01, 3.0000e-01, 9.4868e-02, 3.0000e-02,
           9.4868e-03, 3.0000e-03, 9.4868e-04]]]])


# **Constructing Attention**

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision, torchaudio

# **self.attention block**

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision, torchaudio

class Attention(nn.Module):

  def __init__(self, d_in , d_out):
    super().__init__()
    self.d_in = d_in
    self.d_out = d_out

  def constructing_attention_block(self):





